version: '2'
services:
  angular-social:
    container_name: angular-social
    image: nadjim/angular-social
    networks:
      - social
      - default
    ports:
      - "8070:80"
    labels:
      - "traefik.backend=angular-social"
      - "traefik.docker.network=social"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:web.spring-social.ovh"
      - "traefik.port=80"
networks:
  social:
    external: true
